name: Build wiclax4j

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: azul/zulu-openjdk:15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build JAR
        run: ./gradlew jar --info --stacktrace --build-cache --no-daemon
      - name: Run tests
        run: ./gradlew test --info --stacktrace --build-cache --no-daemon
      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-results
          path: build/reports/tests
      - name: Run static analysis
        run: ./gradlew sonarqube --info --stacktrace --build-cache --no-daemon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: wiclax4j
          path: build/libs/*.jar
