name: Build wiclax4j

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3.13.0
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Build JAR
        run: ./gradlew jar --info --stacktrace --console=plain --build-cache --no-daemon
      - name: Run tests
        run: ./gradlew test --info --stacktrace --console=plain --build-cache --no-daemon
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        continue-on-error: true
        with:
          files: build/test-results/**/*.xml
      - name: Run static analysis
        if: github.ref == 'refs/heads/master'
        run: ./gradlew sonarqube --info --stacktrace --console=plain --build-cache --no-daemon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Upload JAR
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v3.1.3
        with:
          name: wiclax4j
          path: build/libs/*.jar
